feat(6.1): add solution for ch6-1
summary:
- learned about du core utils, used to calcualte disk usage
- revised cut core utils, to extract specific section of lines
- arithmetic operations

diff --git a/ch06/task1/ndu b/ch06/task1/ndu
--- a/ch06/task1/ndu
+++ b/ch06/task1/ndu
@@ -5,3 +5,21 @@ prints a summary of the disk space usage for each directory argument (and any su
 both in terms of bytes, and kilobytes or megabytes (whichever is appropriate).
 '
 
+
+for dir in ${*:-.}; do
+    if [ -a $dir ]; then
+        sizeinblock=$(du -s $dir | cut -f1)
+        sizeinbyte=$((1024*sizeinblock))
+        mbunit=$((1024*1024))
+        echo -n "size of $dir/: $sizeinbyte bytes"
+
+        if ((mbunit<=sizeinbyte)); then
+            echo "($((sizeinbyte/mbunit)) Mb)"
+        else
+            echo "($((sizeinblock)) Kb)"
+        fi
+    else
+        echo "$dir is invalid file or dir"
+        exit 1
+    fi
+done
